### ISSUE TITLE
[Typo / Quick fix] [Data Engineer setup] - Different Ubuntu versions between text and screenshot

### ISSUE THREAD

**Issue by CharlesLclrc** [lewagon/data-engineering-setup#38]
Hi all, 

Ubuntu version should be `Ubuntu 22.04 LTS` as indicated in the text and not the `Ubuntu 20.04 LTS` as displayed in the screenshot below.
Might be confusing during setup day for students 🙃

Old screenshot:
![Screenshot 2023-09-25 at 16 43 48](https://github.com/lewagon/data-engineering-setup/assets/15238122/3e192e45-b9f2-4163-a80e-6cef08ce687c)

New screenshot:
<img width="602" alt="Screenshot 2023-09-25 at 16 51 42" src="https://github.com/lewagon/data-engineering-setup/assets/15238122/0b4bef95-5bc6-4b0a-8661-65245ae2d9af">

**Comment by ogiles1999** [comment]
Thanks updated the image 👍
