### ISSUE TITLE
virtual machine > boot disk

### ISSUE THREAD

**Issue by davydw** [lewagon/data-engineering-setup#43]
## currently recommended

[https://github.com/lewagon/data-engineering-setup/blob/main/macOS.md#virtual-machine-vm](https://github.com/lewagon/data-engineering-setup/blob/main/macOS.md#virtual-machine-vm)
![Screenshot 2024-02-22 at 16 07 34](https://github.com/lewagon/data-engineering-setup/assets/42499767/f57f69d5-9ddd-4666-b01e-d2f0e01eda9b)

## doesn't seem be working correctly
<img width="698" alt="Screenshot 2024-02-22 at 16 07 53" src="https://github.com/lewagon/data-engineering-setup/assets/42499767/e66e3526-aa38-4236-94ea-9d427edd27c5">

**Comment by lorcanrae** [comment]
Seems odd :thinking: 

I've done a few fresh installs over the last few days and didn't encounter this issue. Closing for now.
